# Generated by Django 4.2.9 on 2024-02-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_title_en_category_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
