# Generated by Django 4.2.9 on 2024-03-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_product', '0003_product_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='simple_prod_title_892ba7_idx'),
        ),
    ]
